build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
filter:
    paths:
        - "src/"
    excluded_paths:
        - "tests/"
        - "example/"
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 2
    php_code_coverage: false
        php_loc:
            enabled: true
            excluded_dirs: [tests, vendor]
        php_cpd:
            enabled: true
            excluded_dirs: [tests, vendor]
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
