build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
filter:
    paths:
        - "src/"
    excluded_paths:
        - "tests/"
        - "example/"
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 2
    php_loc:
        enabled: true
        excluded_dirs:
            - 'build'
            - 'tests'
            - 'vendor'
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
