build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          -
            command: 'vendor/bin/phpunit'
            coverage:
              file: 'build/logs/clover.xml'
              format: 'clover'
checks:
  php:
    code_rating: true
    duplication: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
filter:
  excluded_paths: [tests/*]