language: php

os:
  - linux

php:
  - 7.2
  - 7.3
  - 7.4snapshot

# We don't want to run linux commands as super user
sudo: false

install:
  composer install

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/coverage.xml